name: PikaMed
description: PikaMed Mobil Uygulama.

publish_to: "none"

version: 0.1.3

environment:
    sdk: ">=2.17.5 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    font_awesome_flutter: ^10.8.0
    animations: ^2.0.11
    http: ^1.3.0
    package_info_plus: ^8.3.0
    share_plus: ^11.0.0
    easy_url_launcher: ^0.0.7
    community_material_icon: ^5.9.55
    firebase_auth: ^5.5.2
    firebase_core: ^3.13.0
    firebase_analytics: ^11.4.5
    google_sign_in: ^6.3.0
    flutter_svg: ^2.1.0
    firebase_messaging: ^15.2.5
    permission_handler: ^12.0.0+1
    intl: ^0.20.2
    collection: ^1.19.1
    flutter_background: ^1.3.0+1
    flutter_chat_ui: ^1.6.15

dev_dependencies:
    flutter_launcher_icons: ^0.14.3
    flutter_lints: ^5.0.0
    flutter_test:
        sdk: flutter

flutter_icons:
    android: {
        "generate": true
    }
    web: {
        "generate": true
    }
    windows: {
        "generate": true
    }
    image_path: "assets/logo.jpg"

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/fitness_app/
        - assets/hasta/
        - assets/introduction_animation/
        - assets/fonts/
        - assets/

    fonts:
        - family: WorkSans
          fonts:
              - asset: assets/fonts/WorkSans-Regular.ttf
              - asset: assets/fonts/WorkSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/WorkSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/WorkSans-Bold.ttf
                weight: 700
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Bold.ttf
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Medium.ttf
                weight: 400
